### ISSUE TITLE
Processing times in the Iron Plated Blast Furnace

### ISSUE THREAD

**Issue by Nicdel87** [draknyte1/MiscUtilities#12]
Hey, since the Iron Plated Blast Furnace is kind of an upgrade to the Bronze Blast Furnace, wouldn't it make sense that it is slightly faster or atleast working at the same speed? Currently it takes 5 times longer for the Iron BF to make one steel ingot.

**Comment by draknyte1** [comment]
It's actually a downgrade (I know Iron has a higher melting point) due to the fact iron is FAR more abundant than Tin & Copper.

The idea of it is to gain earlier access to steel, at the cost of a longer wait. I personally spent weeks looking for a tin vein when I started playing, made my first Bronze blast furnace from small ores. Would have loved this then, as 11mo later, I still have iron left from those ventures.

**Comment by Nicdel87** [comment]
Thanks for your reply, makes sense. It was a little confusing due to the higher melting point and the fact that you actually make a bigger structure (40 to 32).

**Comment by draknyte1** [comment]
I'll write a better tooltip, to better explain this.
Might refine the time slightly too~
